# Generated by Django 4.2.7 on 2024-01-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_forografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_forografia',
            new_name='data_fotografia',
        ),
    ]
